### ISSUE TITLE
Move to python f strings

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/tilelog#7]
Use f strings instead for .format

**Comment by JoJo10Smith** [comment]
Hi @pnorman is this still something you would like to change. I read the readme and saw that there was difficult testing but changing to f-string shouldn't be too much of an issue. I'd gladly have this issue assigned to me and I can submit a PR for review and testing if that works for you.

**Comment by pnorman** [comment]
Sure, if you want to contribute it should be an easy change, and the existing test coverage should adequately cover all the strings. Just make sure it passes PEP8 format checks

**Comment by pnorman** [comment]
Completed
